# Generated by Django 2.2.14 on 2021-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_address_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
