# Generated by Django 2.2.14 on 2021-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211017_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
