# Generated by Django 2.2.14 on 2021-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_stock_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CH', 'Чийгшүүлэгч тос'), ('TS', 'Цэвэрлэгч'), ('TO', 'Тонер'), ('NT', 'Нарны тос'), ('HE', 'Хөгшрөлтийн эсрэг'), ('GU', 'Гуужуулагч'), ('ES', 'Эссэнц'), ('SE', 'Серум'), ('UA', 'Үс арчилгаа'), ('BA', 'Бие арчилгаа'), ('MA', 'Маск'), ('NB', 'Нүүрний будаг'), ('ZT', 'Зовхины тос')], max_length=2),
        ),
    ]
